Use warp

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,14 +1,7 @@
 name: CI
 
 on:
-  push:
-    branches:
-      - main
-      - release-*
-  pull_request:
-    branches:
-      - main
-      - release-*
+  workflow_dispatch:
 
 permissions:
   contents: read
@@ -25,9 +18,7 @@ jobs:
       fail-fast: false
       matrix:
         os:
-          - ubuntu-latest
-          - windows-latest
-          - macos-14
+          - warpdev-macos-14-arm64-3x
         node-version:
           - '22'
           - '20'
@@ -43,7 +34,7 @@ jobs:
         exclude:
           # No Node 14 on ARM macOS
           - node-version: '14'
-            os: macos-14
+            os: warpdev-macos-14-arm64-3x
 
     runs-on: ${{ matrix.os }}
     name: Test Node ${{ matrix.node-version }} on ${{ matrix.os }}${{ (!matrix.bundle && ' with --no-bundle') || '' }}
@@ -69,236 +60,236 @@ jobs:
           git add tests/baselines/reference
           git diff --staged --exit-code
 
-  lint:
-    runs-on: ubuntu-latest
+  # lint:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: npm ci
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: npm ci
 
-      - name: Linter
-        run: npm run lint
+  #     - name: Linter
+  #       run: npm run lint
 
-  format:
-    runs-on: ubuntu-latest
+  # format:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: npm ci
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: npm ci
 
-      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
-        with:
-          path: ~/.cache/dprint
-          key: ${{ runner.os }}-dprint-${{ hashFiles('package-lock.json', '.dprint.jsonc') }}
-          restore-keys: |
-            ${{ runner.os }}-dprint-
+  #     - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
+  #       with:
+  #         path: ~/.cache/dprint
+  #         key: ${{ runner.os }}-dprint-${{ hashFiles('package-lock.json', '.dprint.jsonc') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-dprint-
 
-      - name: Check formatting
-        run: npx dprint check
+  #     - name: Check formatting
+  #       run: npx dprint check
 
-  browser-integration:
-    runs-on: ubuntu-latest
+  # browser-integration:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: npm ci
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: npm ci
 
-      - name: Installing browsers
-        run: npx playwright install --with-deps
+  #     - name: Installing browsers
+  #       run: npx playwright install --with-deps
 
-      - name: Validate the browser can import TypeScript
-        run: npx hereby test-browser-integration
+  #     - name: Validate the browser can import TypeScript
+  #       run: npx hereby test-browser-integration
 
-  typecheck:
-    runs-on: ubuntu-latest
+  # typecheck:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: npm ci
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: npm ci
 
-      - name: Build src
-        run: npx hereby build-src
+  #     - name: Build src
+  #       run: npx hereby build-src
 
-  smoke:
-    runs-on: ubuntu-latest
+  # smoke:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
 
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: |
-          npm --version
-          # corepack enable npm
-          npm install -g $(jq -r '.packageManager' < package.json)
-          npm --version
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: |
+  #         npm --version
+  #         # corepack enable npm
+  #         npm install -g $(jq -r '.packageManager' < package.json)
+  #         npm --version
 
-      - run: npm ci
+  #     - run: npm ci
 
-      - run: npx hereby lkg
-      - run: |
-          node ./scripts/addPackageJsonGitHead.mjs package.json
-          npm pack
-          mv typescript*.tgz typescript.tgz
-          echo "package=$PWD/typescript.tgz" >> "$GITHUB_OUTPUT"
-        id: pack
+  #     - run: npx hereby lkg
+  #     - run: |
+  #         node ./scripts/addPackageJsonGitHead.mjs package.json
+  #         npm pack
+  #         mv typescript*.tgz typescript.tgz
+  #         echo "package=$PWD/typescript.tgz" >> "$GITHUB_OUTPUT"
+  #       id: pack
 
-      - name: Smoke test
-        run: |
-          cd "$(mktemp -d)"
-          npm init --yes
-          npm install ${{ steps.pack.outputs.package }}
+  #     - name: Smoke test
+  #       run: |
+  #         cd "$(mktemp -d)"
+  #         npm init --yes
+  #         npm install ${{ steps.pack.outputs.package }}
 
-          echo "Testing tsc..."
-          npx tsc --version
+  #         echo "Testing tsc..."
+  #         npx tsc --version
 
-          echo "Testing tsserver..."
-          echo '{"seq": 1, "command": "status"}' | npx tsserver
+  #         echo "Testing tsserver..."
+  #         echo '{"seq": 1, "command": "status"}' | npx tsserver
 
-          node $GITHUB_WORKSPACE/scripts/checkModuleFormat.mjs typescript
-          node $GITHUB_WORKSPACE/scripts/checkModuleFormat.mjs typescript/lib/tsserverlibrary
+  #         node $GITHUB_WORKSPACE/scripts/checkModuleFormat.mjs typescript
+  #         node $GITHUB_WORKSPACE/scripts/checkModuleFormat.mjs typescript/lib/tsserverlibrary
 
-  package-size:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request'
+  # package-size:
+  #   runs-on: ubuntu-latest
+  #   if: github.event_name == 'pull_request'
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-        with:
-          path: pr
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #       with:
+  #         path: pr
 
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-        with:
-          path: base
-          ref: ${{ github.base_ref }}
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #       with:
+  #         path: base
+  #         ref: ${{ github.base_ref }}
 
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: |
-          npm --version
-          # corepack enable npm
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: |
+  #         npm --version
+  #         # corepack enable npm
 
-      - run: |
-          npm install -g $(jq -r '.packageManager' < package.json)
-          npm --version
-        working-directory: ./pr
+  #     - run: |
+  #         npm install -g $(jq -r '.packageManager' < package.json)
+  #         npm --version
+  #       working-directory: ./pr
 
-      - run: npm ci
-        working-directory: ./pr
+  #     - run: npm ci
+  #       working-directory: ./pr
 
-      - run: npm ci
-        working-directory: ./base
+  #     - run: npm ci
+  #       working-directory: ./base
 
-      - run: npx hereby lkg
-        working-directory: ./pr
+  #     - run: npx hereby lkg
+  #       working-directory: ./pr
 
-      - run: npx hereby lkg
-        working-directory: ./base
+  #     - run: npx hereby lkg
+  #       working-directory: ./base
 
-      - run: |
-          echo "See $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID for more info."
-          node ./pr/scripts/checkPackageSize.mjs ./base ./pr >> $GITHUB_STEP_SUMMARY
+  #     - run: |
+  #         echo "See $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID for more info."
+  #         node ./pr/scripts/checkPackageSize.mjs ./base ./pr >> $GITHUB_STEP_SUMMARY
 
-  misc:
-    runs-on: ubuntu-latest
+  # misc:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: npm ci
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: npm ci
 
-      - name: Build scripts
-        run: npx hereby scripts
+  #     - name: Build scripts
+  #       run: npx hereby scripts
 
-      - name: ESLint tests
-        run: npx hereby run-eslint-rules-tests
+  #     - name: ESLint tests
+  #       run: npx hereby run-eslint-rules-tests
 
-  self-check:
-    runs-on: ubuntu-latest
+  # self-check:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: npm ci
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: npm ci
 
-      - name: Build tsc
-        run: npx hereby tsc
+  #     - name: Build tsc
+  #       run: npx hereby tsc
 
-      - name: Clean
-        run: npx hereby clean-src
+  #     - name: Clean
+  #       run: npx hereby clean-src
 
-      - name: Self build
-        run: npx hereby build-src --built
+  #     - name: Self build
+  #       run: npx hereby build-src --built
 
-  baselines:
-    runs-on: ubuntu-latest
+  # baselines:
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
-      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
-        with:
-          node-version: '*'
-          check-latest: true
-      - run: npm ci
+  #   steps:
+  #     - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
+  #     - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
+  #       with:
+  #         node-version: '*'
+  #         check-latest: true
+  #     - run: npm ci
 
-      - name: Remove all baselines
-        run: rm -rf tests/baselines/reference
+  #     - name: Remove all baselines
+  #       run: rm -rf tests/baselines/reference
 
-      - name: Run tests
-        run: npm test &> /dev/null || exit 0
+  #     - name: Run tests
+  #       run: npm test &> /dev/null || exit 0
 
-      - name: Accept baselines
-        run: |
-          npx hereby baseline-accept
-          git add tests/baselines/reference
+  #     - name: Accept baselines
+  #       run: |
+  #         npx hereby baseline-accept
+  #         git add tests/baselines/reference
 
-      - name: Check baselines
-        id: check-baselines
-        run: |
-          function print_diff() {
-            if ! git diff --staged --exit-code --quiet --diff-filter=$1; then
-              echo "$2:"
-              git diff --staged --name-only --diff-filter=$1
-            fi
-          }
+  #     - name: Check baselines
+  #       id: check-baselines
+  #       run: |
+  #         function print_diff() {
+  #           if ! git diff --staged --exit-code --quiet --diff-filter=$1; then
+  #             echo "$2:"
+  #             git diff --staged --name-only --diff-filter=$1
+  #           fi
+  #         }
 
-          if ! git diff --staged --exit-code --quiet; then
-            print_diff ACR "Missing baselines"
-            print_diff MTUXB "Modified baselines"
-            print_diff D "Unused baselines"
-            git diff --staged > fix_baselines.patch
-            exit 1
-          fi
+  #         if ! git diff --staged --exit-code --quiet; then
+  #           print_diff ACR "Missing baselines"
+  #           print_diff MTUXB "Modified baselines"
+  #           print_diff D "Unused baselines"
+  #           git diff --staged > fix_baselines.patch
+  #           exit 1
+  #         fi
 
-      - name: Upload baseline diff artifact
-        if: ${{ failure() && steps.check-baselines.conclusion == 'failure' }}
-        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
-        with:
-          name: fix_baselines.patch
-          path: fix_baselines.patch
+  #     - name: Upload baseline diff artifact
+  #       if: ${{ failure() && steps.check-baselines.conclusion == 'failure' }}
+  #       uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
+  #       with:
+  #         name: fix_baselines.patch
+  #         path: fix_baselines.patch
